name: Build

on:
  push:
#    branches: master

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: "x64"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec
      - name: Upload with build
        uses: actions/upload-artifact@v3
        with:
          name: Windows_weekGenerator
          path: dist/generate_week.exe
      - name: List items
        run: ls -R 
